config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    # Active record validations
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
# Membership Plan
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # Active Record Association
  # Every Profile belongs to one User
  belongs_to :user
  #
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Active Record Associations
  belongs_to :plan
  # Every User has one Profile
  has_one :profile
  # Use hidden field/Stripe card token to help create Stripe customer
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid?
      # Use Stripe gem to send info to Stripe (create/charge customer), returns id
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      # Save the user
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      # Whitelist (accept known good) parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    # Store empty Contact object to help generate Form
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    # When we save the contacts
    if @contact.save
      # Assign variables using Hash syntax for Query String Parameters
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Call method from mailer file
      ContactMailer.contact_email(name, email, body).deliver
      
      # Show Flash notice
      flash[:success] = 'Message sent.'
      # Redirect to the same new contact url
      redirect_to new_contact_path
    else
      flash[:danger] = 'Error occured, message has not been sent.'
      redirect_to new_contact_path
    end
  end
  
  private
    def contact_params
      # White list the parameters
      params.require(:contact).permit(:name, :email, :comments)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        # Define instance variables assigned to Database tables
        # Find method "plucks out" Plan with particular ID
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # Use Rails and Devise gem functionality to prevent url manipulation
  # Before any Action, user must be authenticated (exist/signed in)
  before_action :authenticate_user!
  # Before any Action, user can only be the current one
  before_action :only_current_user
  
  def new
    # Form where a user can fill out their own profile.
    # Find out who is logged in using params Hash (dictionary).
    @user = User.find( params[:user_id] )
    # Demo how to access Query String Parameter added to Path.
    #@variable = params[:hello]
    #
    @profile = Profile.new
  end
  
  def create
    # Actually save the User's info typed into our form.
    # Find out who is logged in using params Hash (dictionary).
    @user = User.find( params[:user_id] )
    # Pass in all data entered into our form fields.
    @profile = @user.build_profile(profile_params)
    
    if @profile.save
      # Flash message for visual feedback
      flash[:success] = "Profile Updated!"
      # Direct to User's "show" page.
      redirect_to user_path( params[:user_id] )
    else
      # Render the "new" action again.
      render action: :new
    end
    
  end
  
  def edit
    # Identify which user's Form we want to edit
    @user = User.find( params[:user_id] )
    # Load the profile for this user into the Form fields
    @profile = @user.profile
  end
  
  def update
    # Identify which user's Form we want to update
    @user = User.find( params[:user_id] )
    # Assign the User's profile
    @profile = @user.profile
    # Pass in all data entered into our form fields.
    if @profile.update_attributes(profile_params)
      # Flash message for visual feedback
      flash[:success] = "Profile Updated!"
      # Redirect user to their Profile page
      redirect_to user_path( params[:user_id] )
    else
      # Render the "edit" action again.
      render action: :edit
    end
  end
  
  private
    def profile_params
      # Whitelist all data entered into our form fields.
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      # Identify the user that is logged in
      @user = User.find( params[:user_id] )
      # Redirect user to the home page, unless they are the current user
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Only when New action (sign up page) occurs, run select_plan function beforehand
  before_filter :select_plan, only: :new
  def create
    # Import all functionality from superclass
    super do |resource|
      if params[:plan]
        # Save value to plan id
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      # Make sure user can't submit a Query String Param value other than 1 or 2
      unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Before any Action, user must be authenticated (exist/signed in).
  before_action :authenticate_user!
  
  def index
    # Find all Users in database.
    @users = User.all
  end
  
  def show
    # Find User in database by their ID.
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1 class="text-center">Contact Us</h1>
        <p class="text-center">Reach out if you have any questions or comments.</p>
        <div class="well">
            <!-- Use Form helpers to generate Form HTML code -->
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>    
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>
                </div>   
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class: 'form-control' %>
                </div>   
                    <%= f.submit 'Submit', class: 'btn btn-default' %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev Match</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class='container'>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-users"></i>
          Dev Match
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? # If logged in, true %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Community", users_path %></li>
            <li><%= link_to "My Account", edit_user_registration_path %></li>
          <% end %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Us", new_contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container"> 
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>
<p>Welcome to Dev Match. We are a community of developers, entrepreneurs, and investors who are interested in meeting one another and sharing ideas.</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
<h1>Welcome to Dev Match</h1>
  <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>
<div class="row">
  <% # Use Devise gem's bool to determine if user is signed in %>
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Your Profile</h2>
        <% # Show Profile links, current_user provided by Devise gem %>
        <% if current_user.profile %>
          <% # Providing current_user or (more literal) user_id: current_user.id gets same result  %>
          <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
        <% else %>
          <p>Create your profile so that you can share your information with the community.</p>
          <%= link_to "Create your profile!", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">The Community</h2>
        <p>Visit the community to meet other developers, entrepreneurs, and investors!</p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    <div class="col-md-6">
      <div class="well">
          <h2 class="text-center">Basic Membership</h2>
          <h4>Sign up for free and get basic access to the community.</h4>
          <br/>
          <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
          <h2 class="text-center">Pro Membership</h2>
          <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
          <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>
  <% end %>  
</div>

app/views/profiles/_form.html.erb
<% # Have to specify path because Profile is singular per User in Routes.rb %>
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
<div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<% # Form for user to create profile, first name, last name. %>
<% # @variable %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
        <div class="well">
            <% # Have to specify path because Profile is singular per User in Routes.rb %>
            <%= form_for @profile, url: user_profile_path do |f| %>
            <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :job_title %>
                <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :phone_number %>
                <%= f.text_field :phone_number, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :contact_email %>
                <%= f.text_field :contact_email, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.submit "Update Profile", class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Dev Match Community</h1>
    <p>Welcome to the Dev Match community. Users must fill out a profile in order to be visible in the community.</p>
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %>
        <li>
          <div class="well row <%= cycle('white-bg', '') %>">
            <div class="col-sm-4 text-center">
              <% if user.profile.avatar %>
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                <% end %>
              <% end %>
            </div>
            <div>
              <%= link_to user do %>
                <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
              <% end %>
              <p>
                <%= user.profile.job_title %> 
                <% if user.plan_id == 2 %>
                  <span class="label label-danger">PRO</span>
                <% end %>
              </p>
            </div>
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar profile-avatar' %>
  </div>
  <div class="col-md-6">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %><br/></h3>
    <div class="well profile-block profile-description">
      <h3>Description</h3>
      <%= @user.profile.description %>
    </div>
    <% if current_user.plan_id == 2 %>
      <div class="well profile-block contact-info">
        <h3>Contact Info</h3>
        <%= @user.profile.phone_number %><br/>
        <%= @user.profile.contact_email %><br/>
      </div>
    <% end %>
  </div>
</div>